---
- hosts: all
  become: true
  become_user: root

  tasks:

    - name: Jenkins server | Copy Jenkins docker compose files and make file
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/vagrant/
        owner: vagrant
        group: vagrant
        mode: '0644'
      loop:
        - docker-compose.yml
        - Makefile
    
    - name: Copy Jenkins init passwd
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/vagrant/
        owner: vagrant
        group: vagrant
        mode: '0754'
      loop:
        - jenkins_init_pass.sh

    - name: Install the packages 
      ansible.builtin.apt:
        pkg: make

    - name: Init docker-compose by - make init
      shell: "make init"

